config/routes.rb
Rails.application.routes.draw do
  resources :enquiries
  devise_for :users
  resources :users
  resources :listings do
    collection do
      get :stats
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "listings#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/enquiry.rb
class Enquiry < ApplicationRecord
  belongs_to :listing

  broadcasts_to ->(enquiry) { [enquiry.listing.user, "enquiries"] }, partial: "enquiries/enquiry_item", inserts_by: :prepend
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many :enquiries

  validates :title, :address, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :listings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
end

app/controllers/enquiries_controller.rb
class EnquiriesController < ApplicationController
  before_action :set_enquiry, only: %i[ show edit update destroy ]

  # GET /enquiries or /enquiries.json
  def index
    @enquiries = Enquiry.all
  end

  # GET /enquiries/1 or /enquiries/1.json
  def show
  end

  # GET /enquiries/new
  def new
    @enquiry = Enquiry.new
  end

  # GET /enquiries/1/edit
  def edit
  end

  # POST /enquiries or /enquiries.json
  def create
    @enquiry = Enquiry.new(enquiry_params)

    if @enquiry.save
      redirect_to enquiry_url(@enquiry), notice: "Enquiry was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /enquiries/1 or /enquiries/1.json
  def update
    if @enquiry.update(enquiry_params)
      redirect_to enquiry_url(@enquiry), notice: "Enquiry was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /enquiries/1 or /enquiries/1.json
  def destroy
    @enquiry.destroy

    redirect_to enquiries_url, notice: "Enquiry was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enquiry
      @enquiry = Enquiry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enquiry_params
      params.require(:enquiry).permit(:name, :email, :message, :listing_id)
    end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: %i[ show edit update destroy ]

  # GET /listings or /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1 or /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings or /listings.json
  def create
    @listing = Listing.new(listing_params)

    if @listing.save
      respond_to do |format|
        format.html { redirect_to listings_url, notice: "Listing was successfully created." }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /listings/1 or /listings/1.json
  def update
    if @listing.update(listing_params)
      redirect_to listings_url, notice: "Listing was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /listings/1 or /listings/1.json
  def destroy
    @listing.destroy

    respond_to do |format|
      format.html { redirect_to listings_url, notice: "Listing was successfully destroyed." }
      format.turbo_stream
    end
  end

  def stats
    sleep 10
  end

private

  # Use callbacks to share common setup or constraints between actions.
  def set_listing
    @listing = Listing.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def listing_params
    params.require(:listing).permit(:title, :address, :available_from)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to user_url(@user), notice: "User was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    if @user.update(user_params)
      redirect_to user_url(@user), notice: "User was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    redirect_to users_url, notice: "User was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :admin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/enquiries/_enquiry.html.erb
<div id="<%= dom_id enquiry %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= enquiry.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Email:</strong>
    <%= enquiry.email %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Message:</strong>
    <%= enquiry.message %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Listing:</strong>
    <%= enquiry.listing_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this enquiry", enquiry, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this enquiry', edit_enquiry_path(enquiry), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/enquiries/_enquiry_item.html.erb
<div class="my-4">
  <div id="<%= dom_id enquiry %>" class="flex justify-between items-center border rounded px-2">
    <p class="my-5">
      <strong class="block font-medium mb-1">Name:</strong>
      <%= enquiry.name %>
    </p>

    <p class="my-5">
      <strong class="block font-medium mb-1">Email:</strong>
      <%= enquiry.email %>
    </p>

    <p class="my-5">
      <strong class="block font-medium mb-1">Message:</strong>
      <%= enquiry.message %>
    </p>

    <p class="my-5">
      <strong class="block font-medium mb-1">Listing:</strong>
      <%= enquiry.listing.title %>
    </p>

    <% if action_name.present? && action_name != "show" %>
      <%= link_to "Show this enquiry", enquiry, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <%= link_to "Edit this enquiry", edit_enquiry_path(enquiry), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
      <hr class="mt-6">
    <% end %>
  </div>
</div>

app/views/enquiries/_form.html.erb
<%= form_with(model: enquiry, class: "contents") do |form| %>
  <% if enquiry.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(enquiry.errors.count, "error") %> prohibited this enquiry from being saved:</h2>

      <ul>
        <% enquiry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :email %>
    <%= form.text_field :email, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :message %>
    <%= form.text_area :message, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :listing_id %>
    <%= form.text_field :listing_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/enquiries/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing enquiry</h1>

  <%= render "form", enquiry: @enquiry %>

  <%= link_to "Show this enquiry", @enquiry, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to enquiries", enquiries_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/enquiries/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Enquiries</h1>
    <%= link_to 'New enquiry', new_enquiry_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="enquiries" class="min-w-full">
    <%= render partial: "enquiry_item", collection: @enquiries, as: :enquiry %>
  </div>
</div>

app/views/enquiries/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New enquiry</h1>

  <%= render "form", enquiry: @enquiry %>

  <%= link_to 'Back to enquiries', enquiries_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/enquiries/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <%= render @enquiry %>

    <%= link_to 'Edit this enquiry', edit_enquiry_path(@enquiry), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this enquiry', enquiry_path(@enquiry), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to enquiries', enquiries_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyTurbo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if notice.present? %>
      <div class="py-2 px-3 bg-green-50 m-5 text-green-500 font-medium rounded-lg text-center" id="notice"><%= notice %></div>
    <% end %>
    <% if alert.present? %>
      <div class="py-2 px-3 bg-red-50 m-5 text-red-500 font-medium rounded-lg text-center" id="alert"><%= alert %></div>
    <% end %>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/listings/_enquiries.html.erb
<%= turbo_stream_from current_user, "enquiries" %>

<h3 class="font-bold text-xl my-4">Enquiries</h3>
<div id="enquiries">
  <%= render partial: "enquiries/enquiry_item", collection: @listing.enquiries, as: :enquiry if current_user == @listing.user %>
</div>

app/views/listings/_form.html.erb
<%= form_with(model: listing, class: "contents") do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
        <% listing.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :address %>
    <%= form.text_area :address, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :available_from %>
    <%= form.date_field :available_from, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/listings/_listing.html.erb
<div id="<%= dom_id listing %>">
  <p class="my-5 font-bold text-2xl">
    <%= listing.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Address:</strong>
    <%= listing.address %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Available from:</strong>
    <%= listing.available_from %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this listing", listing, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this listing', edit_listing_path(listing), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/listings/_listing_item.html.erb
<div class="my-4">
  <%= turbo_frame_tag dom_id(listing) do %>
    <div class="flex justify-between items-center border rounded px-2">
      <p class="my-5">
        <strong class="block font-medium mb-1">Title:</strong>
        <%= listing.title %>
      </p>

      <p class="my-5">
        <strong class="block font-medium mb-1">Address:</strong>
        <%= listing.address %>
      </p>

      <p class="my-5">
        <strong class="block font-medium mb-1">Available from:</strong>
        <%= listing.available_from %>
      </p>

      <div>
        <%= link_to "Show this listing", listing, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium", data: { turbo_frame: "_top" } %>
        <%= link_to 'Edit this listing', edit_listing_path(listing), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
        <%= button_to 'Delete this listing', listing_path(listing), method: :delete, class: "rounded-lg py-3 ml-2 px-5 bg-red-100 inline-block font-medium", form_class: "inline-block" %>
      </div>
    </div>
  <% end %>
</div>

app/views/listings/create.turbo_stream.erb
<%= turbo_stream.prepend "listings", partial: "listings/listing_item", locals: { listing: @listing } %>
<%= turbo_stream.update Listing.new, "" %>

app/views/listings/destroy.turbo_stream.erb
<%= turbo_stream.remove @listing %>

app/views/listings/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing listing</h1>

  <%= turbo_frame_tag dom_id(@listing) do %>
    <%= render "form", listing: @listing %>

    <%= link_to "Cancel", listings_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Show this listing", @listing, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium", data: { turbo_frame: "_top" } %>
  <% end %>
</div>

app/views/listings/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Listings</h1>
    <%= link_to 'New listing', new_listing_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium", data: { turbo_frame: dom_id(Listing.new) } %>
  </div>

  <%= turbo_frame_tag dom_id(Listing.new) do %>
  <% end %>

  <%= turbo_frame_tag "listing_stats", src: stats_listings_path do %>
    <p>Loading stats...</p>
  <% end %>

  <div id="listings" class="min-w-full">
    <%= render partial: "listing_item", collection: @listings, as: :listing %>
  </div>
</div>

app/views/listings/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New listing</h1>

  <%= turbo_frame_tag dom_id(Listing.new) do %>
    <%= render "form", listing: @listing %>

    <%= link_to 'Cancel', listings_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <% end %>
</div>

app/views/listings/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <%= render @listing %>
    <%= render "enquiries" %>

    <%= link_to 'Edit this listing', edit_listing_path(@listing), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this listing', listing_path(@listing), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to listings', listings_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/listings/stats.html.erb
<%= turbo_frame_tag "listing_stats" do %>
  <dl>
    <dt class="inline-block font-bold">Total enquiries:</dt>
    <dd class="inline-block">3000</dd>
  </dl>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, class: "contents") do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :email %>
    <%= form.text_field :email, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :admin %>
    <%= form.check_box :admin, class: "block mt-2 h-5 w-5" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= user.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Email:</strong>
    <%= user.email %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Admin:</strong>
    <%= user.admin %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this user", user, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this user', edit_user_path(user), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/users/_user_item.html.erb
<div class="my-4">
  <div id="<%= dom_id user %>" class="flex justify-between items-center border rounded px-2">
    <p class="my-5">
      <strong class="block font-medium mb-1">Name:</strong>
      <%= user.name %>
    </p>

    <p class="my-5">
      <strong class="block font-medium mb-1">Email:</strong>
      <%= user.email %>
    </p>

    <p class="my-5">
      <strong class="block font-medium mb-1">Admin:</strong>
      <%= user.admin %>
    </p>

    <% if action_name != "show" %>
      <%= link_to "Show this user", user, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <%= link_to 'Edit this user', edit_user_path(user), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing user</h1>

  <%= render "form", user: @user %>

  <%= link_to "Show this user", @user, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to users", users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/users/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Users</h1>
    <%= link_to 'New user', new_user_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="users" class="min-w-full">
    <%= render partial: "user_item", collection: @users, as: :user %>
  </div>
</div>

app/views/users/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New user</h1>

  <%= render "form", user: @user %>

  <%= link_to 'Back to users', users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/users/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <%= render @user %>

    <%= link_to 'Edit this user', edit_user_path(@user), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this user', user_path(@user), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to users', users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>